-- AlterTable
ALTER TABLE "Heart_Rate_Record" ALTER COLUMN "beat" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "ir_Reading" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "redReading" SET DATA TYPE DOUBLE PRECISION;
